### ISSUE TITLE
Diagramas 

### ISSUE THREAD

**Issue by Reyesjessica** [SistemasTecTlaxiaco/actividad-9-diagrama-de-clases-secuencia-equipo-ija#1]
https://drive.google.com/file/d/1Yzq_JaG2sE1YoLHd19sWl92WpDfsPftr/view?usp=drivesdk

**Comment by Luisangelriverosbautista** [comment]
reviasndo cumple su trabajo 29

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
